#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = tapdelay

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	tapdelay.cpp.o \
	tapdelay_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
