#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = diffuse

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	diffuse.cpp.o \
	diffuse_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
