#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = distortion

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	distortion.cpp.o \
	distortion_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
