#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = octaver

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	octaver.cpp.o \
	octaver_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
