#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = compressor

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	compressor.cpp.o \
	compressor_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
