#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = noisegate

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	noisegate.cpp.o \
	noisegate_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
