#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = fourwayswitch

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	fourwayswitch.cpp.o \
	fourwayswitch_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
