#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = reguitar

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	reguitar.cpp.o \
	reguitar_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
