#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = fbdelay

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	fbdelay.cpp.o \
	fbdelay_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
