#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = ditherdist

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	ditherdist.cpp.o \
	ditherdist_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
