#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = distortion2

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	distortion2.cpp.o \
	distortion2_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
