#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = graphiceq

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	graphiceq.cpp.o \
	graphiceq_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
