#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = linkwitz

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	linkwitz.cpp.o \
	linkwitz_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
