#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = overdrive

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	overdrive.cpp.o \
	overdrive_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
