#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = flanger

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	flanger.cpp.o \
	flanger_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
