#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = ensemble

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	ensemble.cpp.o \
	ensemble_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
