#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = distortion3

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	distortion3.cpp.o \
	distortion3_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
