#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = plugintemplate

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	plugintemplate.cpp.o \
	plugintemplate_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
