#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = selfmod

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	selfmod.cpp.o \
	selfmod_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
