#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = autotune

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	autotune.cpp.o \
	autotune_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
