#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = tremvibe

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	tremvibe.cpp.o \
	tremvibe_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
