#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = fbdistortion

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	fbdistortion.cpp.o \
	fbdistortion_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
