#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = doubleswitch

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	doubleswitch.cpp.o \
	doubleswitch_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
