#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = feedback

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	feedback.cpp.o \
	feedback_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
