#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = respectrum

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	respectrum.cpp.o \
	respectrum_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
