#!/usr/bin/make -f

# --------------------------------------------------------------
# Project name, used for binaries

NAME = fourwayrailroad

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	fourwayrailroad.cpp.o \
	fourwayrailroad_dsp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
